### ISSUE TITLE
不要打广告了

### ISSUE THREAD

**Issue by Hooooogeorge** [f8q8/tiku-xuexiqiangguo#4]
![httpst mexxqgfxq](https://user-images.githubusercontent.com/56151692/71834774-f3dc4100-30ea-11ea-8ca7-cb19f4bbbe97.png)

**Comment by f8q8** [comment]
广告，就不要在这里打了。自动学习的软件很多，但是，这个app的监测机制是，会不定期抽查，如果发现学习过程中，有作弊行为，第一次警告、第二次封号，第三次永久封号。
